.TH ABOOK 1 2006-09-06
.nh
.SH NAME
abook \- text-based address book program
.SH SYNOPSIS
.B abook
[ \fIOPTION\fR ]
.SH DESCRIPTION
This manual page documents briefly the
.B abook
program.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.B abook 
is a text-based address book program. It contains Name, Email, Address 
and various Phone fields. It is designed for use with mutt, but can be
equally useful on its own.
.SH OPTIONS
.TP
\fB\-h \-\-help\fP
Show usage.
.TP
\fB\-C \-\-config\fP \fI<filename>\fR
Use an alternative configuration file (default is \fI$HOME/.abook/abookrc\fR).
.TP
\fB\-\-datafile\fP \fI<filename>\fR
Use an alternative addressbook file (default is \fI$HOME/.abook/addressbook\fR).
.TP
\fB\-\-mutt\-query\fP \fI<string>\fR [ \fB\-\-outformat\fP \fI<outputformat>\fR ]
Make a query for mutt (search the addressbook for \fI<string>\fR).
.br
The \fB\-\-datafile\fP option, as documented above, may be used
.BI BEFORE
this option to search a different addressbook file.
.br
Only a subset of the below \fI<outputformat>\fR are allowed: \fBmutt\fP (default), \fBvcard\fP and \fBcustom\fP
.TP
\fB\-\-convert\fP [ \fB\-\-informat\fP \fI<inputformat>\fR ] [ \fB\-\-infile\fP \fI<inputfile>\fR ] [ \fB\-\-outformat\fP \fI<outputformat>\fR ] [ \fB\-\-outfile\fP \fI<outputfile>\fR ]
Converts \fI<inputfile>\fR in \fI<inputformat>\fR to \fI<outputfile>\fR in \fI<outputformat>\fR
(defaults are \fBabook\fP, \fBstdin\fP, \fBtext\fP and \fBstdout\fP).

.br
The following \fIinputformats\fR are supported:
.br
- \fBabook\fP abook native format
.br
- \fBldif\fP ldif / Netscape addressbook
.br
- \fBmutt\fP mutt alias
.br
- \fBpine\fP pine addressbook
.br
- \fBcsv\fP comma separated values
.br
- \fBpalmcsv\fP Palm comma separated values
.br
- \fBvcard\fP VCard addressbook

.br
The following \fIoutputformats\fR are supported:
.br
- \fBabook\fP abook native format
.br
- \fBldif\fP ldif / Netscape addressbook (.4ld)
.br
- \fBmutt\fP mutt alias
.br
- \fBhtml\fP html document
.br
- \fBpine\fP pine addressbook
.br
- \fBvcard\fP VCard addressbook
.br
- \fBcsv\fP comma separated values
.br
- \fBpalmcsv\fP Palm comma separated values
.br
- \fBelm\fP elm alias
.br
- \fBtext\fP plain text
.br
- \fBspruce\fP Spruce address book
.br
- \fBwl\fP Wanderlust address book
.br
- \fBbsdcal\fP BSD calendar
.br
- \fBcustom\fP Custom output format, see below
.TP
\fB\-\-outformatstr\fP \fI<string>\fR
Only used if \fB\-\-mutt\-query\fP \fIor\fR \fB\-\-convert\fP is specified \fIand\fR \fB\-\-outformat\fP=\fIcustom\fR. \fI<string>\fR is a format string allowing placeholders.
.br
A placeholder can be any of the standard fields names (see \fBabookrc\fP(5)) and must be encapsulated by curly brackets.
.br
The default value is "{nick} ({name}): {mobile}"
.br
If \fI<string>\fR starts with \fI!\fR only entries whose all fields from \fI<string>\fR are non-NULL are included.
.TP
\fB\-\-add-email\fP
Read an e-mail message from stdin and add the sender to the addressbook.
.TP
\fB\-\-add-email-quiet\fP
Same as --add-email but doesn't confirm adding.
.TP
\fB\-\-formats\fP
List available formats.

.SH COMMANDS DURING USE
Press '\fB?\fP' during use to get a list of commands.
.SH SEE ALSO
.BR mutt (1),
.BR abookrc (5)
.br
.SH AUTHOR
This manual page was written by Alan Ford <alan@whirlnet.co.uk>,
for the Debian GNU/Linux system (but may be used by others).

.br
.B abook
was written by Jaakko Heinonen <jheinonen@users.sourceforge.net>
